//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryTrave.Maui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoryTrave.Maui.Resources.Localization.Localization.ru", typeof(Localization_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраняйте воспоминания о ваших путешествиях.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статей.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменено:.
        /// </summary>
        internal static string ChangeAt {
            get {
                return ResourceManager.GetString("ChangeAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создано:.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из текущего аккаунта.
        /// </summary>
        internal static string ExitFromAccount {
            get {
                return ResourceManager.GetString("ExitFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста заполните все поля.
        /// </summary>
        internal static string FillError {
            get {
                return ResourceManager.GetString("FillError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзей.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен не может быть нулевым или пустым.
        /// </summary>
        internal static string JwtError {
            get {
                return ResourceManager.GetString("JwtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в аккаунт.
        /// </summary>
        internal static string Login1 {
            get {
                return ResourceManager.GetString("Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваши данные для входа.
        /// </summary>
        internal static string Login2 {
            get {
                return ResourceManager.GetString("Login2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Login3 {
            get {
                return ResourceManager.GetString("Login3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет посещенных мест.
        /// </summary>
        internal static string NoVisitedPlaces {
            get {
                return ResourceManager.GetString("NoVisitedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать аккаунт.
        /// </summary>
        internal static string Registration1 {
            get {
                return ResourceManager.GetString("Registration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните форму для регистрации.
        /// </summary>
        internal static string Registration2 {
            get {
                return ResourceManager.GetString("Registration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string Registration3 {
            get {
                return ResourceManager.GetString("Registration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык приложения.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тему оформления.
        /// </summary>
        internal static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тёмная.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системная.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непредвиденная ошибка.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посещенные места.
        /// </summary>
        internal static string VisitedPlaces {
            get {
                return ResourceManager.GetString("VisitedPlaces", resourceCulture);
            }
        }
    }
}
